version: '3'

services:
  coredns:
    build: .
    image: aisuhua/coredns:latest
    container_name: coredns
    restart: always
    ports:
      - '127.0.0.1:53:53/tcp'
      - '127.0.0.1:53:53/udp'
